//Create 
POST http://localhost:5000/projects/
Content-Type: application/json

{
    "name": "Second Project Test", 
    "description": "This is a text project to see if the routes are working correctly."
}

###

//Get all
GET http://localhost:5000/projects/ 
Content-Type: application/json


###

//Get one
GET http://localhost:5000/projects/688bac8f7efa8d053476e243
Content-Type: application/json

###

//Update 
PUT http://localhost:5000/projects/688bac8f7efa8d053476e243
Content-Type: application/json

{
    "name": "Project Test Changed", 
    "description": "Changed Text Test"
}

###

//Get Stats 
GET  http://localhost:5000/projects/688ecd4b015d533e6bfa78a0/stats
Content-Type: application/json

###

// Add User
POST http://localhost:5000/projects/68b72fdf9b981ddc7b81bcde/addMember
Content-Type: application/json

{
    "user": "68b895c053027560c97e06e7", 
    "role": "member"
}