//Create 
POST http://localhost:5000/tasks/
Content-Type: application/json

{
    "name": "Create Task API 151516", 
    "description": "Task objects must have a start time, default end date, projectID. No check list items.",
    "projectId": "6890ecd84c1f1c74dcd5c3a2",
    "checklist": [
        {
            "description": "Newer project, first checklist item"
        },
        {
            "description": "Newer project, second checklist item"
        }
    ]
}

###

//Get all
GET http://localhost:5000/tasks/ 
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YjcyZTNjOWI5ODFkZGM3YjgxYmNjYSIsImVtYWlsIjoibWVAZW1haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTY5MjQ0MjIsImV4cCI6MTc1NjkyODAyMn0.BwJvvFSjRXaAiRNMrMp4SZ-SdhoKsyk7SIMw8nK43kw


###

//Get one
GET http://localhost:5000/tasks/68b8703941031e67bcca999e
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Yjg3MDEwNDEwMzFlNjdiY2NhOTk4NiIsImVtYWlsIjoicG93ZWxsLTVAaG90bWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc1NjkyNDU0NiwiZXhwIjoxNzU2OTI4MTQ2fQ.i2-nptuU-5Lmao-Aa4HRdy7HjdyMVYJeYtsuNQjFksM

###

//Update 
PUT http://localhost:5000/tasks/68b8703941031e67bcca999e
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Yjg3MDEwNDEwMzFlNjdiY2NhOTk4NiIsImVtYWlsIjoicG93ZWxsLTVAaG90bWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc1NjkyNDU0NiwiZXhwIjoxNzU2OTI4MTQ2fQ.i2-nptuU-5Lmao-Aa4HRdy7HjdyMVYJeYtsuNQjFksM

{
    "description": "description should not be updated"
}

###

//Complete 
PATCH http://localhost:5000/tasks/688c232e8ebf8dae2fdb5be4/complete
Content-Type: application/json

###

//Delete 
DELETE http://localhost:5000/tasks/688c232e8ebf8dae2fdb5be4
Content-Type: application/json