//Create 
POST http://localhost:5000/tasks/
Content-Type: application/json

{
    "name": "Create Task API 151516", 
    "description": "Task objects must have a start time, default end date, projectID. No check list items.",
    "projectId": "688ecd9c015d533e6bfa78a7",
    "checklist": [
        {
            "description": "Newer project, first Task"
        }
    ]
}

###

//Get all
GET http://localhost:5000/tasks/ 
Content-Type: application/json


###

//Get one
GET http://localhost:5000/tasks/688c232e8ebf8dae2fdb5be4
Content-Type: application/json

###

//Update 
PUT http://localhost:5000/tasks/688c232e8ebf8dae2fdb5be4
Content-Type: application/json

{
    "completedDate": "2025-07-31T16:20:00.000Z"
}

###

//Complete 
PATCH http://localhost:5000/tasks/688c232e8ebf8dae2fdb5be4/complete
Content-Type: application/json

###

//Delete 
DELETE http://localhost:5000/tasks/688c232e8ebf8dae2fdb5be4
Content-Type: application/json